### ISSUE TITLE
roku_node:update_status: App address 562859 is not mapped to an appliction.

### ISSUE THREAD

**Issue by fascenda** [bpaauwe/RokuPoly#6]
I've used your RokuPoly for "awhile" now and recently have a new problem.  I think the screensaver (Home) is now being reported with this unexpected APP value 562859.  I am using RokuPremiere.

I have some ISY programs to respond to my Roku channel selection to set some ambient lights behind my TV.  When I return to Home my ISY program doesn't respond since GV1 gets set to this value 562859.  I have to select some other known channel to get my ISY program to notice so my ambient lights will change (or go off which is what I used to get when returning to Home).

Maybe this is known problem with the latest Roku software updates?

**Comment by bpaauwe** [comment]
It doesn't dynamically adjust to changes in applications on the Roku.  

Have you tried re-discovering to remap the applications?  If the screensaver app ID has changed you'd need to do that so that it can create the mapping to know that the it was changed.

**Comment by fascenda** [comment]
Thanks for the quick reply and I think you have the answer. I was experimenting with another TV that has built in Roku and I remembered, I am using the Roku Photo Streams as my screensaver on the Roku Premiere that is exhibiting this problem. I’ll set back to a builtin screensaver and see if that solves it.

I saw the AppID for Roku Photo is a big 6 digit number, though not the number that is showing when it launches as a screensaver. Thus the unrecognized App ID.

**Comment by fascenda** [comment]
Removing that screensaver did not help it still reports 562859 when it's in the "Home" page.  My other Roku (TCL) reports 0 when it's in the Home page.  I did rediscover but neither report an AppID for ScreenSaver so you assign 0 for its value.  Oh well my workaround is just tune some other channel when I want my ambient lights to go off.

[RokuMediaPlayer_10-3-2022_165808.txt](https://github.com/bpaauwe/RokuPoly/files/9699056/RokuMediaPlayer_10-3-2022_165808.txt)

**Comment by fascenda** [comment]
I'm going to experiment a bit and see what I can figure out myself.   I found out what 562859 is from this query:
http://10.0.0.80:8060/query/media-player
```
<player error="false" state="close">
<plugin bandwidth="5000000 bps" id="562859" name="Roku Dynamic Menu"/>
</player>
```
And after the screensaver appears the active-app becomes:
http://10.0.0.80:8060/query/active-app
```
<active-app>
<app id="562859" type="appl" version="7.1.6">Home</app>
<screensaver id="587746" type="ssvr" version="1.4.39">Space Screensaver</screensaver>
</active-app>
```
Though now query/media-player doesn't give me the plugin element so that might not always be available to query.

**Comment by fascenda** [comment]
Now my Roku is back to reporting known AppID and Roku as the text... I can't figure out why but all is well again.  If it returns to reporting Home as the text a solution might be as shown below.
```
<active-app>
<app>Roku</app>
<screensaver id="637097" type="ssvr" version="1.42.0">Roku Photo Streams</screensaver>
</active-app>
```

```
@@ -52,4 +52,7 @@
                 if child.text == 'Roku':
                     return '0'
+                elif child.text == 'Home':
+                    LOGGER.error('active-app reports "Home"')
+                    return '0'
                 elif 'id' in child.attrib:
                     return child.attrib['id']
```

**Comment by fascenda** [comment]
Some other discussion about this behavior.  A change in Roku firmware version 11 and something called Roku Dynamic Menu.  At the moment my Roku has gone back to reporting "Roku" so the problem is temporarily gone for me.

https://github.com/openhab/openhab-addons/pull/12884

**Comment by fascenda** [comment]
After the latest Roku software update my Roku Premiere always says "Home" now.  These are the changes I made to roku_node.py to solve this problem.  I also added a message to tell when the name of the screensaver changes.

```
@@ -18,4 +20,7 @@
         self.apps = apps

+        # debugging the changes in screensaver (app Roku or Home)
+        self.screensaver = 'none'
+
         # call the default init
         super(RokuNode, self).__init__(controller, primary, address, name)
@@ -35,5 +40,5 @@
             self.setDriver('GV1', self.apps[address][1], report=True, force=True)
         else:
-            LOGGER.error('App address ' + str(address) + ' is not mapped to an appliction.')
+            LOGGER.error('App address ' + str(address) + ' is not mapped to an application.')

     # Find the current active application, return it's address or ''
@@ -48,8 +53,22 @@

         tree = ElementTree.fromstring(r.content)
+        # -- debug screensaver changes with app test Home instead of Roku
+        for ss in tree.iter('screensaver'):
+            if 'id' in ss.attrib:
+               LOGGER.debug('self.screensaver was ' + self.screensaver)
+               if self.screensaver != ss.attrib['id']:
+                   self.screensaver = ss.attrib['id']
+                   LOGGER.debug('active-app reports screensaver appid ' + self.screensaver + " named " + ss.text)
+        # -- end debug
         for child in tree.iter('*'):
             if child.tag == 'app':
+                LOGGER.debug('active-app reports text ' + child.text)
+                if 'id' in child.attrib:
+                    LOGGER.debug('active-app reports id ' + child.attrib['id'])
                 if child.text == 'Roku':
                     return '0'
+                elif child.text == 'Home':
+                    LOGGER.debug('active-app text is "Home"')
+                    return '0'
                 elif 'id' in child.attrib:
                     return child.attrib['id']
```
